# Server Configuration
server:
  port: 8080

# These are the VariableConfigurations struct values
variable:
  title: "VDI Calculator"
  titlesub: "by Andr√© Leibovici"
  update: "Calculate"
  about: "About"
  print: "Print"
  guide: "Guide"

# These are the VMConfigurations struct values
vm:
  vmprofilelabel: "Profile"
  vmprofile: { "Task": "1", "Office": "2", "Knowledge": "3", "Power": "4" }
  vmprofileselected: 1
  vmcountlabel: "Number of Desktops"
  vmcount: 2000
  vmcountselected: 2000
  vcpucountlabel: "CPU Count:"
  vcpucount: { "1": "1", "2": "2", "4": "4", "8": "8" }
  vmvcpucountselected: "1"
  vcpumhzlabel: "Average vCPU MHz"
  vcpumhz: 500
  vcpumhzselected: 500
  vcpumhztooltip: "Average MHz used by each vCPU in a VM"
  vmpercorecountlabel: "VMs per Core"
  vmpercorecount:
    {
      "1": "1",
      "2": "2",
      "4": "4",
      "5": "5",
      "6": "6",
      "7": "7",
      "8": "8",
      "9": "9",
      "10": "10",
      "11": "11",
      "12": "12",
      "13": "13",
      "14": "14",
      "15": "15",
      "16": "16",
      "17": "17",
      "18": "18",
      "19": "19",
      "20": "20",
    }
  vmpercorecountselected: "5"
  displaycountlabel: "Display Count:"
  displaycount: { "1": "1", "2": "2", "4": "4" }
  displayresolutionlabel: "Display Resolution:"
  displayresolution: { "1280x800": "1", "1920x1200": "2", "2560x1600": "3" }
  displayresolutionselected: "2"
  memorysizelabel: "Memory Size (MB)"
  memorysize: 1536
  memorysizeselected: 1536
  videoram: { "Off": "0", "64": "64", "128": "128", "256": "256", "512": "512" }
  videoramlabel: "3D Graphics (MB)"
  videoramselected: "0"
  disksizelabel: "Disk Size (GB)"
  disksize: 100
  disksizeselected: 100
  iopscount: 6
  iopscountselected: 6
  iopscountlabel: "Steady State IOps"
  iopscounttooltip: "Number of IOps during steady state"
  iopsreadratio: 20
  iopsreadratioselected: 20
  iopsreadratiolabel: "IOps Read Ratio (%)"
  iopsreadratiotooltip: "Percentual of IO reads during steady state"
  clonesizerefreshrate:
    {
      "Off": "0",
      "10": "10",
      "20": "20",
      "30": "30",
      "40": "40",
      "50": "50",
      "60": "60",
      "70": "70",
      "80": "80",
      "90": "90",
    }
  clonesizerefreshratetooltip: "Linked clone disk capacity utilized. Off=Full Clone"
  clonesizerefreshratelabel: "Clone Refresh Rate (%)"
  clonesizerefreshrateselected: "0"

# This is the profile for Task user
vmprofile01:
  vcpucountselected: "1"
  vcpumhz: 500
  vmpercorecountselected: "5"
  memorysize: 1536
  displaycountselected: "1"
  displayresolutionselected: "2"
  videoramselected: "0"
  disksizeselected: 100
  iopscountselected: 6
  iopsreadratioselected: 20
  clonesizerefreshrateselected: "0"

# This is the profile for Office user
vmprofile02:
  vcpucountselected: "1"
  vcpumhz: 500
  vmpercorecountselected: "5"
  memorysize: 2048
  displaycountselected: "1"
  displayresolutionselected: "2"
  videoramselected: "64"
  disksizeselected: 100
  iopscountselected: 8
  iopsreadratioselected: 20
  clonesizerefreshrateselected: "0"

# This is the profile for Knowledge user
vmprofile03:
  vcpucountselected: "2"
  vcpumhz: 315
  vmpercorecountselected: "4"
  memorysize: 2048
  displaycountselected: "1"
  displayresolutionselected: "2"
  videoramselected: "64"
  disksizeselected: 100
  iopscountselected: 9
  iopsreadratioselected: 20
  clonesizerefreshrateselected: "0"

# This is the profile for Power user
vmprofile04:
  vcpucountselected: "2"
  vcpumhz: 625
  vmpercorecountselected: "2"
  memorysize: 4096
  displaycountselected: "2"
  displayresolutionselected: "3"
  videoramselected: "128"
  disksizeselected: 100
  iopscountselected: 11
  iopsreadratioselected: 20
  clonesizerefreshrateselected: "0"

# These are the HostConfigurations struct values
host:
  socketcountlabel: "Sockets per Host"
  socketcount: { "1": "1", "2": "2", "4": "4", "6": "6", "8": "8", "10": "10" }
  socketcountselected: 2
  socketcorescountlabel: "Cores per Socket"
  socketcorescount:
    {
      "2": "2",
      "4": "4",
      "6": "6",
      "8": "8",
      "10": "10",
      "12": "12",
      "14": "14",
      "16": "16",
      "18": "18",
      "20": "20",
      "24": "24",
      "32": "32",
      "64": "64",
    }
  socketcorescountselected: 12
  memoryoverhead: 1
  memoryoverheadselected: 1
  memoryoverheadlabel: "Memory Overhead (GB)"
  memoryoverheadtooltip: "Memory used by other host processes"
  coresoverhead: 0
  coresoverheadselected: 0
  coresoverheadlabel: "Cores Overhead"
  coresoverheadtooltip: "Cores used by other host processes"

# These are the StorageConfigurations struct values
storage:
  capacityoverhead: { "0": "0", "5": "5", "10": "10", "20": "20", "30": "30" }
  capacityoverheadlabel: "Capacity Overhead (%)"
  capacityoverheadselected: "5"
  capacityoverheadtooltip: "Aditional storage capacity"
  datastorevmcount: "100"
  datastorevmcountlabel: "VMs per Datastore"
  datastorevmcountselected: "100"
  datastorevmcounttooltip: "Number of VMs per datastore"
  deduperatio: 0
  deduperatiolabel: "Dedupe Ratio (%)"
  deduperatioselected: 0
  deduperatiotooltip: "Deduplication ratio across VMs"
  raidtype: { "5": "5", "6": "6", "10": "10" }
  raidtypelabel: "Raid Level"
  raidtypeselected: "6"

# These are the VirtualizationConfigurations struct values
virtualization:
  clusterhostsize: { "8": "8", "16": "16", "32": "32", "64": "64" }
  clusterhostsizelabel: "Cluster Size"
  clusterhostsizeselected: 8
  clusterhostsizetooltip: "Number of hosts per cluster"
  managementservervmcount: 2000
  managementservervmcountlabel: "VM Limit"
  managementservervmcountselected: 2000
  managementservervmcounttooltip: "Number of VMs per management server"

# These are the HostResultsConfiguration struct values
hostresults:
  countlabel: "Number of Hosts"
  hostclockusedlabel: "Host CPU (GHz)"
  hostmemorylabel: "Host Memory (GB)"
  hostvmcountlabel: "VMs per Host"

# These are the StorageResultsConfiguration struct values
storageresults:
  storagecapacitylabel: "Storage Capacity (TB)"
  storagedatastorecountabel: "Number of Datastores"
  storagedatastoresizelabel: "Datastore Size (TB)"
  storagedatastorefroentendiopslabel: "Datastore Frontend IOps"
  storagedatastorebackendiopslabel: "Datastore Backend IOps"
  storagefrontendiopslabel: "Storage Frontend IOps"
  storagebackendiopslabel: "Storage Backend IOps"


  # These are the VirtualizationResultsConfiguration struct values
virtualizationresults:
  clustercountlabel: "Number of Clusters"
  Managementservercountlabel: "Number of Management Servers"
